services:
  mongodb:
    image: mongo:latest
    networks:
      - easyshop-network
    ports:
      - 27017:27017
    container_name: mongo
    volumes:
      - easyshop-volume:/data/db
    restart: always

  easyshop-app:
    build: 
      context: .
    container_name: easyshop
    networks:
      - easyshop-network
    ports:
      - 3000:3000
    environment:
      - NEXTAUTH_URL=http://localhost:3000
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api
      - MONGODB_URI=mongodb://mongo:27017/easyshop
      - JWT_SECRET=your-secure-jwt-secret-key
    restart: always
    depends_on:
      - mongodb


networks:
  easyshop-network: 
volumes:
  easyshop-volume: 
